# Generated by Django 2.2 on 2021-06-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20210613_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='ingredients',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='instructions',
            field=models.CharField(max_length=2048),
        ),
    ]
