# Generated by Django 2.2 on 2021-06-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_auto_20210613_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
