# Generated by Django 2.2 on 2021-06-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_favorites_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='recipe_app.User'),
        ),
    ]
